### ISSUE TITLE
Request: Include default code format settings

### ISSUE THREAD

**Issue by JeffreyWardman** [AnnaliseAI/pythonpackagecookie#5]
Request to include a .vscode folder and settings.json with the following:
```
"python.formatting.provider": "yapf",
 "python.formatting.yapfArgs": [
 "--style={ based_on_style: google, column_limit: 120 }"
 ],
 "autoDocstring.docstringFormat": "docblockr",
```

Note that the autoDocstring requires the Python Docstring Generator extension in VSCode.

**Comment by StephenHogg** [comment]
Can we just put in like a `.pylintrc` or something instead of specifically using VSCode to do it?
